/** Enemy archetypes and their AI behaviour profiles. */

export type EnemyId =
  | 'scout'
  | 'assault'
  | 'heavy'
  | 'sniper'
  | 'missile'
  | 'shield'
  | 'hunter'
  | 'elite'
  | 'raider'
  | 'fortress'
  | 'wraith'
  | 'colossus';

export type AiArchetype =
  | 'aggressive' // closes fast, fires on the move
  | 'balanced' // advances using cover, engages at mid range
  | 'brawler' // slow push, high pressure, ignores cover
  | 'sniper' // keeps max range, needs LOS, repositions after shots
  | 'artillery' // stays far, lobs splash over walls
  | 'guardian' // holds position, defensive shield cycles
  | 'flanker' // paths around the player to hit weak sides
  | 'raider' // prioritises the HQ over the player
  | 'boss'; // scripted multi-phase patterns

export interface EnemyDef {
  id: EnemyId;
  name: string;
  codename: string;
  desc: string;
  hp: number;
  armor: number; // flat % reduction 0..0.8
  speed: number;
  accel: number;
  size: number;
  damage: number;
  fireDelay: number;
  projSpeed: number;
  projRadius: number;
  pellets: number;
  spread: number;
  splash: number;
  score: number;
  xp: number;
  coins: number;
  archetype: AiArchetype;
  /** Preferred engagement distance in world units. */
  idealRange: number;
  sightRange: number;
  reaction: number;
  accuracy: number; // 0..1 aim error scaling
  shield?: { amount: number; regen: number; cooldown: number };
  abilities?: ('charge' | 'mine' | 'summon' | 'burst' | 'teleport' | 'laser' | 'missiles' | 'shockwave' | 'enrage')[];
  eliteChance: number;
  colors: { hull: string; hull2: string; tread: string; accent: string; glow: string };
  tier: number;
  boss?: boolean;
  phases?: number;
  dropsPowerup: number;
}

export const ENEMIES: Record<EnemyId, EnemyDef> = {
  scout: {
    id: 'scout',
    name: 'Scout',
    codename: 'VIPER',
    desc: 'Fast, fragile, fearless. Rushes in packs and fires on the move.',
    hp: 34,
    armor: 0,
    speed: 138,
    accel: 620,
    size: 22,
    damage: 9,
    fireDelay: 0.62,
    projSpeed: 330,
    projRadius: 3,
    pellets: 1,
    spread: 0.1,
    splash: 0,
    score: 120,
    xp: 12,
    coins: 6,
    archetype: 'aggressive',
    idealRange: 90,
    sightRange: 400,
    reaction: 0.24,
    accuracy: 0.55,
    eliteChance: 0.1,
    colors: { hull: '#e8c25a', hull2: '#a8863a', tread: '#4a4034', accent: '#ffe9a3', glow: '#ffd166' },
    tier: 1,
    dropsPowerup: 0.05,
  },
  assault: {
    id: 'assault',
    name: 'Assault Tank',
    codename: 'ANVIL',
    desc: 'Standard line unit. Uses cover, advances methodically, accurate at mid range.',
    hp: 72,
    armor: 0.08,
    speed: 96,
    accel: 460,
    size: 26,
    damage: 15,
    fireDelay: 1.05,
    projSpeed: 350,
    projRadius: 4,
    pellets: 1,
    spread: 0.04,
    splash: 0,
    score: 200,
    xp: 20,
    coins: 10,
    archetype: 'balanced',
    idealRange: 190,
    sightRange: 440,
    reaction: 0.34,
    accuracy: 0.72,
    eliteChance: 0.12,
    colors: { hull: '#d96b4a', hull2: '#94432c', tread: '#3d3029', accent: '#ffb59a', glow: '#ff6b3d' },
    tier: 1,
    dropsPowerup: 0.07,
  },
  heavy: {
    id: 'heavy',
    name: 'Heavy Tank',
    codename: 'BULWARK',
    desc: 'Slow fortress on treads. Huge shells, thick plate, telegraphed volleys.',
    hp: 190,
    armor: 0.28,
    speed: 58,
    accel: 260,
    size: 32,
    damage: 34,
    fireDelay: 1.9,
    projSpeed: 290,
    projRadius: 6,
    pellets: 1,
    spread: 0.02,
    splash: 34,
    score: 420,
    xp: 42,
    coins: 22,
    archetype: 'brawler',
    idealRange: 150,
    sightRange: 420,
    reaction: 0.5,
    accuracy: 0.8,
    eliteChance: 0.15,
    colors: { hull: '#7d8c9e', hull2: '#4e5b6b', tread: '#2c333c', accent: '#b9d4ff', glow: '#5b8dff' },
    tier: 2,
    dropsPowerup: 0.14,
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    codename: 'LONGSHOT',
    desc: 'Holds long sightlines with a charged rail shot. Relocates after every kill attempt.',
    hp: 52,
    armor: 0.05,
    speed: 74,
    accel: 380,
    size: 24,
    damage: 30,
    fireDelay: 2.3,
    projSpeed: 640,
    projRadius: 3.4,
    pellets: 1,
    spread: 0.005,
    splash: 0,
    score: 340,
    xp: 34,
    coins: 18,
    archetype: 'sniper',
    idealRange: 330,
    sightRange: 620,
    reaction: 0.62,
    accuracy: 0.95,
    abilities: ['charge'],
    eliteChance: 0.12,
    colors: { hull: '#5fc9a8', hull2: '#35806a', tread: '#243a34', accent: '#b6ffe8', glow: '#3dffc0' },
    tier: 2,
    dropsPowerup: 0.12,
  },
  missile: {
    id: 'missile',
    name: 'Missile Tank',
    codename: 'HORNET',
    desc: 'Fires slow tracking missiles from beyond your reach. Kill it before it locks.',
    hp: 88,
    armor: 0.1,
    speed: 70,
    accel: 300,
    size: 27,
    damage: 26,
    fireDelay: 2.6,
    projSpeed: 210,
    projRadius: 5,
    pellets: 2,
    spread: 0.22,
    splash: 52,
    score: 380,
    xp: 38,
    coins: 20,
    archetype: 'artillery',
    idealRange: 300,
    sightRange: 560,
    reaction: 0.55,
    accuracy: 0.6,
    abilities: ['missiles'],
    eliteChance: 0.12,
    colors: { hull: '#b57ad6', hull2: '#724491', tread: '#33263f', accent: '#e6c6ff', glow: '#c07bff' },
    tier: 2,
    dropsPowerup: 0.13,
  },
  shield: {
    id: 'shield',
    name: 'Shield Tank',
    codename: 'AEGIS',
    desc: 'Cycles a frontal energy barrier. Break the shield or hit it from behind.',
    hp: 120,
    armor: 0.15,
    speed: 82,
    accel: 380,
    size: 28,
    damage: 17,
    fireDelay: 1.25,
    projSpeed: 340,
    projRadius: 4,
    pellets: 1,
    spread: 0.05,
    splash: 0,
    score: 400,
    xp: 40,
    coins: 21,
    archetype: 'guardian',
    idealRange: 160,
    sightRange: 440,
    reaction: 0.4,
    accuracy: 0.74,
    shield: { amount: 110, regen: 26, cooldown: 6.5 },
    eliteChance: 0.15,
    colors: { hull: '#6ba8e8', hull2: '#3d6a9c', tread: '#26333f', accent: '#bfe4ff', glow: '#4ea8ff' },
    tier: 2,
    dropsPowerup: 0.14,
  },
  hunter: {
    id: 'hunter',
    name: 'Hunter',
    codename: 'STALKER',
    desc: 'Flanks aggressively, uses brush for concealment and strikes your rear plate.',
    hp: 84,
    armor: 0.12,
    speed: 126,
    accel: 560,
    size: 25,
    damage: 21,
    fireDelay: 0.9,
    projSpeed: 400,
    projRadius: 4,
    pellets: 1,
    spread: 0.05,
    splash: 0,
    score: 440,
    xp: 44,
    coins: 24,
    archetype: 'flanker',
    idealRange: 120,
    sightRange: 480,
    reaction: 0.28,
    accuracy: 0.82,
    abilities: ['mine'],
    eliteChance: 0.18,
    colors: { hull: '#d95f8f', hull2: '#8f3a5c', tread: '#3a2530', accent: '#ffb3d1', glow: '#ff5c9d' },
    tier: 3,
    dropsPowerup: 0.16,
  },
  elite: {
    id: 'elite',
    name: 'Elite Guard',
    codename: 'PRAETOR',
    desc: 'Veteran unit with hardened composite armor and a burst cannon.',
    hp: 165,
    armor: 0.26,
    speed: 108,
    accel: 520,
    size: 28,
    damage: 22,
    fireDelay: 0.78,
    projSpeed: 430,
    projRadius: 4.5,
    pellets: 3,
    spread: 0.16,
    splash: 0,
    score: 620,
    xp: 62,
    coins: 34,
    archetype: 'balanced',
    idealRange: 170,
    sightRange: 500,
    reaction: 0.26,
    accuracy: 0.9,
    abilities: ['burst'],
    shield: { amount: 70, regen: 18, cooldown: 8 },
    eliteChance: 0,
    colors: { hull: '#e0e6f0', hull2: '#8d97a8', tread: '#333a45', accent: '#fff3b0', glow: '#ffd447' },
    tier: 3,
    dropsPowerup: 0.32,
  },
  raider: {
    id: 'raider',
    name: 'Raider',
    codename: 'JACKAL',
    desc: 'Ignores you and sprints for the HQ. Intercept it or lose the base.',
    hp: 60,
    armor: 0.05,
    speed: 148,
    accel: 640,
    size: 23,
    damage: 18,
    fireDelay: 0.7,
    projSpeed: 360,
    projRadius: 4,
    pellets: 1,
    spread: 0.08,
    splash: 0,
    score: 300,
    xp: 30,
    coins: 16,
    archetype: 'raider',
    idealRange: 70,
    sightRange: 700,
    reaction: 0.2,
    accuracy: 0.62,
    eliteChance: 0.1,
    colors: { hull: '#e89b3c', hull2: '#a06322', tread: '#3d3020', accent: '#ffdca6', glow: '#ffab3c' },
    tier: 2,
    dropsPowerup: 0.1,
  },
  wraith: {
    id: 'wraith',
    name: 'Wraith',
    codename: 'SPECTRE',
    desc: 'Phase-capable recon unit. Blinks across the arena and fires plasma lances.',
    hp: 140,
    armor: 0.2,
    speed: 132,
    accel: 600,
    size: 26,
    damage: 24,
    fireDelay: 0.95,
    projSpeed: 460,
    projRadius: 4.5,
    pellets: 1,
    spread: 0.03,
    splash: 0,
    score: 700,
    xp: 70,
    coins: 38,
    archetype: 'flanker',
    idealRange: 150,
    sightRange: 520,
    reaction: 0.24,
    accuracy: 0.9,
    abilities: ['teleport'],
    eliteChance: 0,
    colors: { hull: '#8f7bff', hull2: '#5a4bb0', tread: '#2b2545', accent: '#d9d0ff', glow: '#a08bff' },
    tier: 4,
    dropsPowerup: 0.35,
  },
  fortress: {
    id: 'fortress',
    name: 'THE FORTRESS',
    codename: 'SIEGE PRIME',
    desc: 'A rolling bunker. Twin cannons, missile racks, shield cycling and a brutal enrage.',
    hp: 1100,
    armor: 0.34,
    speed: 46,
    accel: 180,
    size: 58,
    damage: 24,
    fireDelay: 1.15,
    projSpeed: 320,
    projRadius: 7,
    pellets: 2,
    spread: 0.1,
    splash: 46,
    score: 4000,
    xp: 420,
    coins: 260,
    archetype: 'boss',
    idealRange: 210,
    sightRange: 800,
    reaction: 0.35,
    accuracy: 0.85,
    shield: { amount: 240, regen: 40, cooldown: 11 },
    abilities: ['missiles', 'summon', 'shockwave', 'enrage'],
    eliteChance: 0,
    colors: { hull: '#8d6f5a', hull2: '#5b4636', tread: '#2a211a', accent: '#ffc46b', glow: '#ff8c2e' },
    tier: 5,
    boss: true,
    phases: 3,
    dropsPowerup: 1,
  },
  colossus: {
    id: 'colossus',
    name: 'COLOSSUS',
    codename: 'IRON GOD',
    desc: 'Experimental super-heavy. Laser sweeps, minefields and an unstoppable charge.',
    hp: 1850,
    armor: 0.4,
    speed: 54,
    accel: 210,
    size: 66,
    damage: 30,
    fireDelay: 1.0,
    projSpeed: 360,
    projRadius: 7.5,
    pellets: 2,
    spread: 0.14,
    splash: 54,
    score: 6500,
    xp: 700,
    coins: 420,
    archetype: 'boss',
    idealRange: 180,
    sightRange: 820,
    reaction: 0.3,
    accuracy: 0.88,
    shield: { amount: 340, regen: 55, cooldown: 12 },
    abilities: ['laser', 'charge', 'mine', 'summon', 'enrage'],
    eliteChance: 0,
    colors: { hull: '#6f7d8c', hull2: '#414c58', tread: '#22272e', accent: '#7ce7ff', glow: '#37c9ff' },
    tier: 5,
    boss: true,
    phases: 4,
    dropsPowerup: 1,
  },
};

// `raider` is declared above with a cast so the Record stays exhaustive at runtime.
export const ENEMY_LIST: EnemyDef[] = Object.values(ENEMIES);

export const getEnemy = (id: EnemyId): EnemyDef => ENEMIES[id] ?? ENEMIES.assault;

export const NORMAL_ENEMIES: EnemyId[] = [
  'scout',
  'assault',
  'heavy',
  'sniper',
  'missile',
  'shield',
  'hunter',
  'elite',
  'raider',
  'wraith',
];

export const BOSS_IDS: EnemyId[] = ['fortress', 'colossus'];

